receivers:
  jaeger:
    protocols:
      thrift_http:
  statsd:
    endpoint: 0.0.0.0:8125
    is_monotonic_counter: true
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:9090

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      exporters: [logging]
    metrics:
      receivers: [otlp, statsd]
      exporters: [logging, prometheus]
