receivers:
  jaeger:
    protocols:
      thrift_http:
  statsd:
    endpoint: 0.0.0.0:8125
    is_monotonic_counter: true
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    verbosity: detailed
  jaeger:
    endpoint: opencodeco-jaeger:14250
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:9090

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [logging, jaeger]
    metrics:
      receivers: [statsd]
      exporters: [logging, prometheus]
