services:
  opencodeco-mysql:
    container_name: opencodeco-mysql
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: opencodeco
    volumes:
      - opencodeco-mysql:/var/lib/mysql

  opencodeco-phpmyadmin:
    container_name: opencodeco-phpmyadmin
    image: phpmyadmin:5.2
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=opencodeco-mysql
      
networks:
  default:
    name: opencodeco
    external: true
      
volumes:
  opencodeco-mysql:
    name: opencodeco-mysql
