services:
  opencodeco-kafka:
    container_name: opencodeco-kafka
    image: bitnami/kafka:3.5
    ports:
      - ${KAFKA_PORT}:9092
    volumes:
      - opencodeco-kafka:/bitnami
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@opencodeco-kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  opencodeco-kafka-ui:
    container_name: opencodeco-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - ${KAFKA_UI_PORT}:8080
    depends_on:
      - opencodeco-kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./kui-config.yml:/etc/kafkaui/dynamic_config.yaml

networks:
  default:
    name: opencodeco
    external: true

volumes:
  opencodeco-kafka:
    name: opencodeco-kafka
