services:
  opencodeco-redis:
    container_name: opencodeco-redis
    image: redis:7.0
    ports:
      - ${REDIS_PORT}:6379

  opencodeco-redisinsight:
    container_name: opencodeco-redisinsight
    image: redislabs/redisinsight:1.14.0
    ports:
      - ${REDISINSIGHT_PORT}:8001
      
networks:
  default:
    name: opencodeco
    external: true
