version: '3'
services:
  opencodeco-redis:
    container_name: opencodeco-redis
    image: redis:7.0
    ports:
      - 127.0.0.1:6379:6379

  opencodeco-redisinsight:
    container_name: opencodeco-redisinsight
    image: redislabs/redisinsight:1.14.0
    ports:
      - 127.0.0.1:8032:8001
      
networks:
  default:
    name: opencodeco
    external: true
